# Generated by Django 4.0.4 on 2023-02-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id_company', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='extra',
            fields=[
                ('id_extra', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('altitude', models.DecimalField(decimal_places=1, max_digits=12)),
                ('ebikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('last_updated', models.IntegerField()),
                ('normal_bikes', models.IntegerField()),
                ('payment_terminal', models.BooleanField()),
                ('post_code', models.CharField(max_length=20)),
                ('renting', models.IntegerField()),
                ('returning', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('uid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=1, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=1, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('empty_slots', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('id_station', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=1, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=1, max_digits=12)),
                ('name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDatos.extra')),
            ],
        ),
        migrations.CreateModel(
            name='network',
            fields=[
                ('gbfs_href', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('id_network', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.ManyToManyField(to='GestionDatos.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDatos.location')),
                ('stations', models.ManyToManyField(to='GestionDatos.station')),
            ],
        ),
        migrations.AddField(
            model_name='extra',
            name='payment',
            field=models.ManyToManyField(to='GestionDatos.payment'),
        ),
    ]
