# Generated by Django 4.0.4 on 2023-02-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id_company',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
