# Generated by Django 4.0.4 on 2023-02-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDatos', '0002_alter_company_id_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='timestamp',
            field=models.CharField(max_length=200),
        ),
    ]
