# Generated by Django 4.0.4 on 2023-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDatos', '0004_representantelegal_titular_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_proyecto',
            field=models.CharField(max_length=5000),
        ),
    ]
