# Generated by Django 4.0.4 on 2023-02-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDatos', '0005_alter_proyecto_descripcion_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_actual',
            field=models.CharField(max_length=500),
        ),
    ]
