# Generated by Django 4.0.4 on 2023-02-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDatos', '0006_alter_proyecto_estado_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='encargado',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto_inversion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(max_length=500),
        ),
    ]
